---
- name: Deploy CONAN
  hosts: all
  vars:
    conan_dir: /opt/conan

  tasks:
    - name: Create CONAN data directory
      become: true
      ansible.builtin.file:
        path: "{{ conan_dir }}/data"
        state: directory
        owner: "{{ ansible_facts.getent_passwd.joachim.2 }}"
        group: "{{ ansible_facts.getent_group.family.2 }}"
        mode: "0775"

    - name: Create CONAN Quadlet
      become: true
      containers.podman.podman_container:
        name: conan
        state: quadlet
        image: localhost/conan:latest
        env:
          TZ: Europe/Paris
        publish:
          - "127.0.0.1:8080:80"
        volume:
          - "{{ conan_dir }}/data:/var/www/html/data:Z"
        quadlet_options:
          - |
            [Service]
            Restart=always
            RestartSec=5s
