# Generated by Django 6.0.6 on 2026-07-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concerts", "0003_concert_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="concert",
            name="lieu",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
