# Generated by Django 6.0.6 on 2026-07-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concerts", "0004_add_lieu_to_concert"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concert",
            name="lieu",
            field=models.TextField(blank=True, default=""),
        ),
    ]
